// UI primitives barrel — components generated by codegen.layout stage.
// Currently empty; all exports will be wired once Button, Input, Select,
// Modal, Toast, Spinner, StarRating, Badge are codegen'd.
export {};
